./protoc -I=./../../Server/protocol --cpp_out=./../../Test/Classes/Proto ./../../Server/protocol/cs_protocol.proto
./protoc -I=./../../Server/Data --cpp_out=./../../Test/Classes/GameData ./../../Server/Data/gameconfig.proto
./protoc -I=./../../Server/Data --cpp_out=./../../Test/Classes/GameData ./../../Server/Data/square.proto
./protoc -I=./../../Server/Data --cpp_out=./../../Test/Classes/GameData ./../../Server/Data/formation.proto
./protoc -I=./../../Server/Data --cpp_out=./../../Test/Classes/GameData ./../../Server/Data/weight.proto
./protoc -I=./../../Server/Data --cpp_out=./../../Test/Classes/GameData ./../../Server/Data/character.proto
./protoc -I=./../../Server/Data --cpp_out=./../../Test/Classes/GameData ./../../Server/Data/skill.proto
./protoc -I=./../../Server/Data --cpp_out=./../../Test/Classes/GameData ./../../Server/Data/stage.proto
./protoc -I=./../../Server/Data --cpp_out=./../../Test/Classes/GameData ./../../Server/Data/battle_show.proto
cp -f ../../Server/Data/gameconfig.db ../../Test/Resources/GameData/gameconfig.db
cp -rf ../../Server/Data/square ../../Test/Resources/GameData
cp -rf ../../Server/Data/formation ../../Test/Resources/GameData
cp -rf ../../Server/Data/weight ../../Test/Resources/GameData
cp -rf ../../Server/Data/character ../../Test/Resources/GameData
cp -rf ../../Server/Data/skill ../../Test/Resources/GameData
cp -rf ../../Server/Data/stage ../../Test/Resources/GameData
cp -rf ../../Server/Data/battle_show ../../Test/Resources/GameData